name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, macos-10.15, windows-2019]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.5.0
        env:
          CIBW_ARCHS: native
          CIBW_SKIP: pp* *musllinux*
          # CIBW_REPAIR_WHEEL_COMMAND: ""
          # Package the DLL dependencies in the wheel for windows (done by default for the other platforms).
          # delvewheel cannot mangle the libraries, stripping does not work.
          # CIBW_BEFORE_BUILD_WINDOWS: pip install delvewheel
          # CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel show {wheel} && delvewheel repair -w {dest_dir} {wheel} --no-mangle-all"
          # Run the tests.
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {package}/tests/test_kpls_auto.py::Test::test_exp_KPLS --import-mode=append -s
          # CIBW_TEST_COMMAND: python -m unittest {package}/smt
          # CIBW_TEST_COMMAND: python -m unittest discover -s {package}/smt
            # python -c smt.surrogate_models.rmtsclib.PyRMTB
            # python -m smt.surrogate_models.RMTB
          CIBW_BUILD_VERBOSITY: 3
          # CIBW_ENVIRONMENT: CXXFLAGS='-O2'

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
